=== myBraavos/starknet-meta/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+$"
        },
        "displayName": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,50}$"
        },
        "description": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,300}$"
        },
        "host": {
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "minProperties": 1,
                    "properties": {
                        "mainnet-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha-2": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "others": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        }
                    }
                }
            ]
        },
        "contracts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "tag": {
                        "type": "string"
                    },
                    "implements": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": ["erc721", "erc20", "erc1155"]
                        }
                    },
                    "addresses": {
                        "type": "object",
                        "properties": {
                            "mainnet-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha-2": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": ["tag", "addresses"]
            }
        },
        "categories": {
            "type": "array",
            "items": { "$ref": "#/definitions/Category" }
        }
    },
    "definitions": {
        "Category": {
            "type": "string",
            "enum": ["nft", "defi", "mobile", "infra", "gamefi", "digitalid"]
        }
    },
    "required": [
        "id",
        "displayName",
        "description",
        "host",
        "contracts",
        "categories"
    ]
}

=== myBraavos/starknet-meta/repository/10kswap/metadata.json
{
  "id": "10kswap",
  "displayName": "10KSwap",
  "host": "10kswap.com",
  "description": "10KSwap is a Layer 2 AMM protocol building on Starknet",
  "categories": [
    "defi"
  ],
  "contracts": [
    {
      "tag": "10k_swap_address",
      "addresses": {
        "goerli-alpha": [
          "0x00975910cd99bc56bd289eaaa5cee6cd557f0ddafdb2ce6ebea15b158eb2c664"
        ],
        "mainnet-alpha": [
          "0x07a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1"
        ]
      }
    },
    {
      "tag": "10k_swap_factory",
      "addresses": {
        "goerli-alpha": [
          "0x06c31f39524388c982045988de3788530605ed08b10389def2e7b1dd09d19308"
        ],
        "mainnet-alpha": [
          "0x01c0a36e26a8f822e0d81f20a5a562b16a8f8a3dfd99801367dd2aea8f1a87a2"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/yagi/metadata.json
{
  "id": "yagi",
  "displayName": "Yagi Finance",
  "host": "yagi.fi",
  "description": "Yagi is a network of keepers on Starknet L2 that automate protocol actions.",
  "categories": [
    "defi",
    "infra"
  ],
  "contracts": [
    {
      "tag": "yagi_vault",
      "implements": [
        "erc20"
      ],
      "addresses": {
        "goerli-alpha": [
          "0xdeacbc83303420ea41fd3720c205a7779b025f9f3f6515ac10cabb666ff207"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/stakepool/metadata.json
{
  "id": "stakepool",
  "displayName": "Braavos Stake Pooling",
  "host": "braavos.app",
  "description": "Braavos Stake Pooling allows you to enjoy liquid ETH staking while enjoying low gas fees",
  "categories": [
    "defi",
    "mobile"
  ],
  "contracts": [
    {
      "tag": "braavos_stake_pool",
      "addresses": {
        "mainnet-alpha": [
          "0x074c31eb40b4f704814a8b9764889f21a7b12464765c4e235ade9b7dfff63660"
        ]
      }
    },
    {
      "tag": "braavos_stake_boost",
      "addresses": {
        "mainnet-alpha": [
            "0x5abfa46fe9bf3323dfe801da51174729c2b3dd060b80575b29c015245899d74"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/starknetid/metadata.json
{
  "id": "starknetid",
  "displayName": "Starknet.id",
  "host": {
    "goerli-alpha": "goerli.app.starknet.id",
    "mainnet-alpha": "app.starknet.id"
  },
  "description": "Identity and naming service for starknet",
  "categories": [
    "nft",
    "digitalid"
  ],
  "contracts": [
    {
      "tag": "starknet_id_address",
      "addresses": {
        "goerli-alpha": [
          "0x0798e884450c19e072d6620fefdbeb7387d0453d3fd51d95f5ace1f17633d88b",
          "0x0783a9097b26eae0586373b2ce0ed3529ddc44069d1e0fbc4f66d42b69d6850d"
        ],
        "mainnet-alpha": [
          "0x05dbdedc203e92749e2e746e2d40a768d966bd243df04a6b712e222bc040a9af"
        ]
      }
    },
    {
      "tag": "starknet_id_domain_address",
      "addresses": {
        "goerli-alpha": [
          "0x5cf267a0af6101667013fc6bd3f6c11116a14cda9b8c4b1198520d59f900b17",
          "0x003bab268e932d2cecd1946f100ae67ce3dff9fd234119ea2f6da57d16d29fce"
        ],
        "mainnet-alpha": [
          "0x06ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678"
        ]
      }
    },
    {
      "tag": "starknet_id_quest",
      "addresses": {
        "goerli-alpha": [
          "0x068c6b0cab1423338dd3ee6affb14a8e53ec0c64c27075d6137f6b8d2b4ccc73"
        ]
      }
    },
    {
      "tag": "starknet_id_subdomain_address",
      "addresses": {
        "goerli-alpha": [
          "0x0660b2cd3c93528d4edf790610404414ba3f03e0d45c814d686d628583cb34de"
        ],
        "mainnet-alpha": [
          "0x3448896d4a0df143f98c9eeccc7e279bf3c2008bda2ad2759f5b20ed263585f"
        ]
      }
    },
    {
      "tag": "starknet_id_verifier",
      "addresses": {
        "goerli-alpha": [
          "0x4d546c8d60cfd591557ac0613be5ceeb0ea6f797e7d11c0b5160d145fa3089f"
        ],
        "mainnet-alpha": [
          "0x0480258f58d43fb73936f803780047a0f6d0a563697d80bd3f95b603f9c8b1c8"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/flex/metadata.json
{
    "id": "flex",
    "displayName": "Flex",
    "description":  "The 1st Dynamic Marketplace for Starknet",
    "host": "flexing.gg",
    "categories": ["nft", "mobile"],
    "contracts": [
      {
        "tag": "flex_marketplace",
        "addresses": {
          "mainnet-alpha": [
            "0x703d3e6ea6736b59857e4a2107d439dc7a8b28adfbd48b5e87c024a7df3a51a"
          ]
        }
      }
    ]
  }

=== myBraavos/starknet-meta/repository/realms/metadata.json
{
  "id": "realms",
  "displayName": "Realms",
  "host": {
    "goerli-alpha": "goerli-beta.realms.world",
    "mainnet-alpha": "realms.world"
  },
  "description": "The Realms Autonomous World is an on-chain open gaming environment being terraformed by the Bibliotheca DAO, that evolved out of the Loot Universe",
  "categories": [
    "gamefi", "nft"
  ],
  "contracts": [
    {
      "tag": "realms_lords",
      "implements": [
        "erc20"
      ],
      "addresses": {
        "goerli-alpha": [
          "0x0488c4091e5c57309f4acdce4f746898a82f50351d8c85278ad2e877c8c032bd"
        ],
        "mainnet-alpha": [
          "0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49"
        ]
      }
    },
    {
      "tag": "lords_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x042331a29c53f6084f08964cbd83b94c1a141e6d14009052d55b03793b21d5b3"
        ],
        "mainnet-alpha": [
          "0x7c76a71952ce3acd1f953fd2a3fda8564408b821ff367041c89f44526076633"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/ninth/metadata.json
{
  "id": "ninth",
  "displayName": "The Ninth",
  "host": "ninth.gg",
  "description": "The Ninth is a Player-Made and revolutionary Real-Time Evolving Game that gives you the power to shape the game's development and determine the future. You'll be in control like never before in this fully-on-chain and crypto-native game with endless possibilities and a constantly evolving ecosystem.",
  "categories": [
    "gamefi"
  ],
  "contracts": [
    {
      "tag": "ninth_token",
      "implements": [
        "erc20"
      ],
      "addresses": {
        "goerli-alpha": [
          "0x06fbd3f381ddcdf541d361a938717e97ff12ba3c77e4f96f9517d79055123293"
        ]
      }
    },
    {
      "tag": "ninth_koma",
      "addresses": {
        "goerli-alpha": [
          "0x0192e5bc40dc9ef4ce7b7dcdf07c8c6adda7d138989ef918caf741eb93a85e49"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/briq/metadata.json
{
  "id": "briq",
  "displayName": "briq",
  "host": "briq.construction",
  "description": "NFT building and composition protocol. Get some briqs and build the dream.",
  "categories": [
    "nft"
  ],
  "contracts": [
    {
      "tag": "briq_world",
      "addresses": {
        "mainnet-alpha": [
          "0x01ea16366a82e211a9b9045725309a5080c0260d5caf45c58836fc61b42501f5"
        ]
      }
    },
    {
      "tag": "briq_factory",
      "addresses": {
        "mainnet-alpha": [
          "0x075341b8090a4257f22dafffe3a4cb882006bd26302720d6a80a1fde154a3430"
        ]
      }
    },
    {
      "tag": "briq_token",
      "addresses": {
        "mainnet-alpha": [
          "0x02417eb26d02947416ed0e9d99c7a023e3565fc895ee21a0a0ef88a524a665d6"
        ]
      }
    },
    {
      "tag": "box_nft_starknet_planet",
      "addresses": {
        "mainnet-alpha": [
          "0x073e3b5e6c7924f752a158c2b07f606bd5b885029da0ac1e3cde254985303f50"
        ]
      }
    },
    {
      "tag": "box_nft_briqmas",
      "addresses": {
        "mainnet-alpha": [
          "0x069699ce808b5459a3b652b5378f8c141e1dc79e10f4e7b486439fd989b7dfb1"
        ]
      }
    },
    {
      "tag": "booklet_ducks_everywhere",
      "addresses": {
        "mainnet-alpha": [
          "0x03311cdef78f70c1b13568e6dabda043c5e9d2736c0c02a35aa906d91d69836b"
        ]
      }
    },
    {
      "tag": "booklet_starknet_planet",
      "addresses": {
        "mainnet-alpha": [
          "0x02fd50e1bdd7400a8fc97eb63aa4f3423a7ec72ebe78d413ce410ec60a35afea"
        ]
      }
    },
    {
      "tag": "booklet_briqmas",
      "addresses": {
        "mainnet-alpha": [
          "0x04bbb2000c80ff79c2aa3b8aa83ee69c103469181a19d01d7f3ee4313a8031"
        ]
      }
    },
    {
      "tag": "booklet_ducks_frens",
      "addresses": {
        "mainnet-alpha": [
          "0x035d3f5be7b3b06a2d02a539faecd45bf4a04644aee7290359bd595047929a92"
        ]
      }
    },
    {
      "tag": "set_nft",
      "addresses": {
        "mainnet-alpha": [
          "0x03f96949d14c65ec10e7544d93f298d0cb07c498ecb733774f1d4b2adf3ffb23"
        ]
      }
    },
    {
      "tag": "set_nft_ducks_everywhere",
      "addresses": {
        "mainnet-alpha": [
          "0x04fa864a706e3403fd17ac8df307f22eafa21b778b73353abf69a622e47a2003"
        ]
      }
    },
    {
      "tag": "set_nft_starknet_planet",
      "addresses": {
        "mainnet-alpha": [
          "0x0e9b982bdcbed7fa60e5bbf733249ff58da9fe935067656e8175d694162df3"
        ]
      }
    },
    {
      "tag": "set_nft_briqmas",
      "addresses": {
        "mainnet-alpha": [
          "0x012a6eeb4a3eecaf16667e2b630963a4c215cdf3715fb271370a02ed6e8c1942"
        ]
      }
    },
    {
      "tag": "set_nft_1155_ducks_frens",
      "addresses": {
        "mainnet-alpha": [
          "0x0433a83c97c083470a1e2f47e24cbc53c4a225f69ffc045580a7279e7f077c79"
        ]
      }
    },
    {
      "tag": "briq_token (old)",
      "addresses": {
        "goerli-alpha": [
          "0x01317354276941f7f799574c73fd8fe53fa3f251084b4c04d88cf601b6bd915e"
        ],
        "mainnet-alpha": [
          "0x00247444a11a98ee7896f9dec18020808249e8aad21662f2fa00402933dce402"
        ]
      }
    },
    {
      "tag": "briq_set (old)",
      "implements": [
        "erc721"
      ],
      "addresses": {
        "goerli-alpha": [
          "0x0266b1276d23ffb53d99da3f01be7e29fa024dd33cd7f7b1eb7a46c67891c9d0"
        ],
        "mainnet-alpha": [
          "0x01435498bf393da86b4733b9264a86b58a42b31f8d8b8ba309593e5c17847672"
        ]
      }
    },
    {
      "tag": "briq_booklet (old)",
      "addresses": {
        "mainnet-alpha": [
          "0x05faa82e2aec811d3a3b14c1f32e9bbb6c9b4fd0cd6b29a823c98c7360019aa4"
        ]
      }
    },
    {
      "tag": "briq_box (old)",
      "addresses": {
        "mainnet-alpha": [
          "0x01e1f972637ad02e0eed03b69304344c4253804e528e1a5dd5c26bb2f23a8139"
        ]
      }
    },
    {
      "tag": "briq_auctions (old)",
      "addresses": {
        "mainnet-alpha": [
          "0x00b9bb7650a88f7e375ae8d31d48b4d4f13c6c34344839837d7dae7ffcdd3df0",
          "0x01712e3e3f133b26d65a3c5aaae78e7405dfca0a3cfe725dd57c4941d9474620"
        ]
      }
    },
    {
      "tag": "briq_attr_registry (old)",
      "addresses": {
        "mainnet-alpha": [
          "0x008d4f5b0830bd49a88730133a538ccaca3048ccf2b557114b1076feeff13c11"
        ]
      }
    },
    {
      "tag": "briq_shape_registry (old)",
      "addresses": {
        "mainnet-alpha": [
          "0x04848d0dd8a296352ba4fe100fed9d6f44cbd0a8d360b7d551d986732a14791a"
        ]
      }
    }
  ]
}
