=== myBraavos/starknet-meta/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+$"
        },
        "displayName": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,50}$"
        },
        "description": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,300}$"
        },
        "host": {
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "minProperties": 1,
                    "properties": {
                        "mainnet-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha-2": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "others": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        }
                    }
                }
            ]
        },
        "contracts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "tag": {
                        "type": "string"
                    },
                    "implements": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": ["erc721", "erc20", "erc1155"]
                        }
                    },
                    "addresses": {
                        "type": "object",
                        "properties": {
                            "mainnet-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha-2": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": ["tag", "addresses"]
            }
        },
        "categories": {
            "type": "array",
            "items": { "$ref": "#/definitions/Category" }
        }
    },
    "definitions": {
        "Category": {
            "type": "string",
            "enum": ["nft", "defi", "mobile", "infra", "gamefi", "digitalid"]
        }
    },
    "required": [
        "id",
        "displayName",
        "description",
        "host",
        "contracts",
        "categories"
    ]
}

=== myBraavos/starknet-meta/repository/nimbora/metadata.json
{
    "id": "nimbora",
    "displayName": "Nimbora",
    "host": {
        "goerli-alpha": "testnet.nimbora.io",
        "mainnet-alpha": "app.nimbora.io/referral/?ref=zJ5q5ztQ"
    },
    "description": "Nimbora is a highly efficient platform that offers the opportunity to interact with favorite Layer 1 (L1) protocols at a fraction of the cost of Layer 2 (L2) solutions. Nimbora makes DeFi actions a simple 1-click process and offers faster transactions and much lower gas fees.",
    "categories": [
        "defi"
    ],
    "contracts": [
        {
            "tag": "275% Trove",
            "addresses": {
                "mainnet-alpha": [
                    "0x03580a65260563b5511ddf2eafb83d6b309dce7fc25271df8c040a437f09a399"
                ]
            }
        },
        {
            "tag": "400% Trove",
            "addresses": {
                "mainnet-alpha": [
                    "0x02a67288e48a8c4e2881aee422da7841fc11fef195e0a81f929871c77f07509d"
                ]
            }
        },
        {
            "tag": "Nimbora Pendle EtherFi Eth",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x316ec509f7ad89b7e6e03d15a436df634454f95e815536d616af03edc850fa3"
                ]
            }
        },
        {
            "tag": "Nimbora Savings Dai",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x4380de5819e2e989b5e8b978ea2811fd36fdbc5c12fcfb3a2b444098888665"
                ]
            }
        },
        {
            "tag": "Nimbora Pendle Puffer Eth",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x357cba05d61beb5fe378429d25013dc5fe0f67878b541747b0675c5ebecee1"
                ]
            }
        },
        {
            "tag": "Nimbora Pendle Flux Usdc",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x52bdb85297e6b0c87d8ec98c5195a4324ff731676d64d9bee2e9e8710e8ea52"
                ]
            }
        },
        {
            "tag": "Nimbora Pendle Aave Usdt",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x40daf98c49c6104002428958456208455a03825198fa7646bd793a321f4fc82"
                ]
            }
        }
    ]
}

=== myBraavos/starknet-meta/repository/myswap/metadata.json
{
  "id": "myswap",
  "displayName": "mySwap",
  "host": "www.myswap.xyz",
  "description": "mySwap is the first AMM built on Starknet. You can swap tokens and deposit your funds in liquidity pools to earn high yield.",
  "categories": [
    "defi",
    "mobile"
  ],
  "contracts": [
    {
      "tag": "myswap_address_legacy",
      "addresses": {
        "goerli-alpha": [
          "0x71faa7d6c3ddb081395574c5a6904f4458ff648b66e2123b877555d9ae0260e"
        ]
      }
    },
    {
      "tag": "myswap_address_2",
      "addresses": {
        "goerli-alpha": [
          "0x018a439bcbb1b3535a6145c1dc9bc6366267d923f60a84bd0c7618f33c81d334"
        ],
        "mainnet-alpha": [
          "0x018a439bcbb1b3535a6145c1dc9bc6366267d923f60a84bd0c7618f33c81d334",
          "0x10884171baf1914edc28d7afb619b40a4051cfae78a094a55d230f19e944a28"
        ]
      }
    },
    {
      "tag": "myswap_liquidity_tokens",
      "addresses": {
        "goerli-alpha": [
          "0x895a214b06582050056ad5dd29dd8086a82d9159f023ab4d21d6fa1a2985eb",
          "0x1550ce85c20f616af7eec81b3a1c4d4cc2ca99140e68b8092256bdff15e7df9",
          "0x21312730d9bac8678adfaf52f7a4471decbca5b502ac05c223e627e78c7087a"
        ],
        "mainnet-alpha": [
          "0x22b05f9396d2c48183f6deaf138a57522bcc8b35b67dee919f76403d1783136",
          "0x7c662b10f409d7a0a69c8da79b397fd91187ca5f6230ed30effef2dceddc5b3"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/starkgate/metadata.json
{
  "id": "starkgate",
  "displayName": "StarkGate",
  "host": {
    "goerli-alpha": "goerli.starkgate.starknet.io",
    "mainnet-alpha": "starkgate.starknet.io"
  },
  "description": "StarkGate is the Ethereum <-> Starknet token bridge developed by StarkWare",
  "categories": [
    "defi",
    "infra"
  ],
  "contracts": [
    {
      "tag": "eth_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x073314940630fd6dcda0d772d4c972c4e0a9946bef9dabf4ef84eda8ef542b82"
        ],
        "mainnet-alpha": [
          "0x073314940630fd6dcda0d772d4c972c4e0a9946bef9dabf4ef84eda8ef542b82"
        ]
      }
    },
    {
      "tag": "dai_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x0278f24c3e74cbf7a375ec099df306289beb0605a346277d200b791a7f811a19"
        ],
        "mainnet-alpha": [
          "0x001108cdbe5d82737b9057590adaf97d34e74b5452f0628161d237746b6fe69e",
          "0x075ac198e734e289a6892baa8dd14b21095f13bf8401900f5349d5569c3f6e60"
        ]
      }
    },

    {
      "tag": "usdc_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x001d5b64feabc8ac7c839753994f469704c6fabdd45c8fe6d26ed57b5eb79057"
        ],
        "mainnet-alpha": [
          "0x05cd48fccbfd8aa2773fe22c217e808319ffcc1c5a6a463f7d8fa2da48218196"
        ]
      }
    },

    {
      "tag": "wbtc_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x072eeb90833bae233a9585f2fa9afc99c187f0a3a82693becd6a4d700b37fc6b"
        ],
        "mainnet-alpha": [
          "0x07aeec4870975311a7396069033796b61cd66ed49d22a786cba12a8d76717302"
        ]
      }
    },

    {
      "tag": "usdt_bridge",
      "addresses": {
        "goerli-alpha": [
          "0x071d54658ca3c6ccd84ff958adb7498b2e71ba008e29b643983221ed2bd71b69"
        ],
        "mainnet-alpha": [
          "0x074761a8d48ce002963002becc6d9c3dd8a2a05b1075d55e5967f42296f16bd0"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/pyramid/metadata.json
{
    "id": "pyramid",
    "displayName": "Pyramid",
    "host": "pyramid.market",
    "description":  "Discover a new dimension on Pyramid NFT Marketplace, Collect and trade, unique digital assets powered by Dolven Labs and StarkGuardians Built on Starknet",
    "categories": ["nft", "infra"],
    "contracts": [
      {
        "tag": "marketplace",
        "addresses": {
          "mainnet-alpha": [
            "0x364847c4f39b869760a8b213186b5b553127e9420e594075d13d1ce8a1d9157"
          ]
        }
      }
    ]
  }

=== myBraavos/starknet-meta/repository/starkdefi/metadata.json
{
  "id": "starkdefi",
  "displayName": "StarkDeFi",
  "host": "app.starkdefi.com",
  "description":"StarkDefi is a permissionless and trustless hub of comprehensive DeFi solutions built to leverage ZK-Rollup on Starknet",
  "categories": [
    "defi"
  ],
  "contracts": [
    {
      "tag": "starkdefi_address",
      "addresses":{
        "mainnet-alpha":[
          "0x02721f5ab785ae5e13b276ca9d41e859b7b150440a288a7826ba5e27dd05e08e"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/zklend/metadata.json
{
	"id": "zklend",
	"displayName": "zkLend",
	"host": {
	  "mainnet-alpha": "app.zklend.com"
	},
	"description": "zkLend is the native L2 money-market protocol built on Starknet, combining zk-rollup scalability, superior transaction speed, and cost-savings with Ethereumâ€™s security.",
	"categories": [
	  "defi"
	],
	"contracts": [
	  {
		"tag": "to_be_provided_by_dev",
		"addresses": {
		  "mainnet-alpha": [
			"0x_to_be_provided_by_dev"
		  ]
		}
	  },
	  {
		"tag": "to_be_provided_by_dev",
		"addresses": {
		  "mainnet-alpha": [
			"0x_to_be_provided_by_dev"
		  ]
		}
	  }
	]
  }

=== myBraavos/starknet-meta/repository/aspect/metadata.json
{
  "id": "aspect",
  "displayName": "Aspect",
  "host": {
    "goerli-alpha": "testnet.aspect.co",
    "mainnet-alpha": "aspect.co"
  },
  "description": "Aspect is an NFT marketplace powered by Starknet. Buy, Sell, and Create in the meta economy.",
  "categories": [
    "nft",
    "mobile"
  ],
  "contracts": [
    {
      "tag": "aspect_collection",
      "implements": [
        "erc721"
      ],
      "addresses": {
        "goerli-alpha": [
          "0x04e34321e0bce0e4ff8ff0bcb3a9a030d423bca29a9d99cbcdd60edb9a2bf03a",
          "0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c"
        ],
        "mainnet-alpha": [
          "0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c"
        ]
      }
    },
    {
      "tag": "aspect_operator",
      "addresses": {
        "goerli-alpha": [
          "0x37c320cf53f24747cb6afd1c23d0bf9ca33dcf8840764df11f8f8c8c0cd685c",
          "0x05841326c67a6806308d60c74d69e8a6895a254689f2e01a2f3c133e6ce733c5",
          "0x006fcf30a53fdc33c85ab428d6c481c5d241f1de403009c4e5b66aeaf3edc890"
        ],
        "mainnet-alpha": [
          "0x02a92f0f860bf7c63fb9ef42cff4137006b309e0e6e1484e42d0b5511959414d"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/myswapcl/metadata.json
{
  "id": "myswapcl",
  "displayName": "mySwap CL",
  "host": "www.myswap.xyz",
  "description": "Swap or provide liquidity using the most advanced AMM on Starknet.",
  "categories": [
    "defi",
    "mobile"
  ],
  "contracts": [
    {
      "tag": "myswap_cl_address",
      "addresses": {
        "goerli-alpha": [
	"0x0436924c4ed166d3c283d516adc424976cfccba108e3a0e3f3fc1ef319e23aa7",
	"0x052d99ab5835a0c295567dcdd40e9e281378d26d02ecca7b31e33dea99bc02ea"
        ],
        "mainnet-alpha": [
	"0x01114c7103e12c2b2ecbd3a2472ba9c48ddcbf702b1c242dd570057e26212111",
	"0x00fff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff"
        ]
      }
    }
  ]
}
