=== myBraavos/starknet-meta/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+$"
        },
        "displayName": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,50}$"
        },
        "description": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,300}$"
        },
        "host": {
            "oneOf": [
                {
                    "type": "string",
                    "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "minProperties": 1,
                    "properties": {
                        "mainnet-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "goerli-alpha-2": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        },
                        "others": {
                            "type": "string",
                            "pattern": "^(?=.{1,253})(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                        }
                    }
                }
            ]
        },
        "contracts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "tag": {
                        "type": "string"
                    },
                    "implements": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": ["erc721", "erc20", "erc1155"]
                        }
                    },
                    "addresses": {
                        "type": "object",
                        "properties": {
                            "mainnet-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            },
                            "goerli-alpha-2": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^0x[0-9a-fA-F]{1,64}$"
                                }
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": ["tag", "addresses"]
            }
        },
        "categories": {
            "type": "array",
            "items": { "$ref": "#/definitions/Category" }
        }
    },
    "definitions": {
        "Category": {
            "type": "string",
            "enum": ["nft", "defi", "mobile", "infra", "gamefi", "digitalid"]
        }
    },
    "required": [
        "id",
        "displayName",
        "description",
        "host",
        "contracts",
        "categories"
    ]
}

=== myBraavos/starknet-meta/repository/troves/metadata.json
{
    "id": "troves",
    "displayName": "Troves",
    "host": {
        "mainnet-alpha": "troves.fi"
    },
    "description": "Troves is a DeFi yield aggregator on Starknet that automatically invests your assets across various DeFi protocols within a given strategy to maximise your returns!",
    "categories": [
        "defi"
    ],
    "contracts": [
        {
            "tag": "Master",
            "addresses": {
                "mainnet-alpha": [
                    "0x050314707690c31597849ed66a494fb4279dc060f8805f21593f52906846e28e"
                ]
            }
        },
        {
            "tag": "Ekubo xSTRK/STRK",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x01f083b98674bc21effee29ef443a00c7b9a500fd92cf30341a3da12c73f2324"
                ]
            }
        },
        {
            "tag": "xSTRK Sensei",
            "implements": [
                "erc721"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x07023a5cadc8a5db80e4f0fde6b330cbd3c17bbbf9cb145cbabd7bd5e6fb7b0b"
                ]
            }
        },
        {
            "tag": "Vesu Fusion ETH",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x05eaf5ee75231cecf79921ff8ded4b5ffe96be718bcb3daf206690ad1a9ad0ca"
                ]
            }
        },
        {
            "tag": "Vesu Fusion STRK",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x07fb5bcb8525954a60fde4e8fb8220477696ce7117ef264775a1770e23571929"
                ]
            }
        },
        {
            "tag": "Vesu Fusion USDC",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x00a858c97e9454f407d1bd7c57472fc8d8d8449a777c822b41d18e387816f29c"
                ]
            }
        },
        {
            "tag": "Vesu Fusion USDT",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x0115e94e722cfc4c77a2f15c4aefb0928c1c0029e5a57570df24c650cb7cec2c"
                ]
            }
        },
        {
            "tag": "Auto-Compounding STRK (deprecated)",
            "addresses": {
                "mainnet-alpha": [
                    "0x00541681b9ad63dff1b35f79c78d8477f64857de29a27902f7298f7b620838ea"
                ]
            }
        },
        {
            "tag": "Auto-Compounding USDC (deprecated)",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x016912b22d5696e95ffde888ede4bd69fbbc60c5f873082857a47c543172694f"
                ]
            }
        },
        {
            "tag": "STRK Sensei (deprecated)",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x020d5fc4c9df4f943ebb36078e703369c04176ed00accf290e8295b659d2cea6"
                ]
            }
        },
        {
            "tag": "USDC Sensei (deprecated)",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x04937b58e05a3a2477402d1f74e66686f58a61a5070fcc6f694fb9a0b3bae422"
                ]
            }
        }
        
    ]
}

=== myBraavos/starknet-meta/repository/starkex/metadata.json
{
  "id": "StarkEx",
  "displayName": "StarkEx",
  "host": "starkex.org",
  "description": "StarkEx——AMM,Liquidity Farms,and Reward pools on StarkNet. StarkEx is also a community-based and open-source ecosystem for DeFi! Say goodbye to CeFi!",
  "categories": [
    "defi"
  ],
  "contracts": [
    {
      "tag": "starkex_address",
      "addresses": {
        "mainnet-alpha": [
          "0x07ebd0e95dfc4411045f9424d45a0f132d3e40642c38fdfe0febacf78cc95e76"
        ]
      }
    },
    {
      "tag": "starkex_factory",
      "addresses": {
        "mainnet-alpha": [
          "0x07df3bce30857e8f9c08bcd9d9668df34166e94dd968db6e2920b870c4410e34"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/atomiq/metadata.json
{
  "id": "atomiq",
  "displayName": "Atomiq Bridge",
  "host": {
    "mainnet-alpha": "app.atomiq.exchange"
  },
  "description": "Native cross chain BTC-Starknet bridge",
  "categories": [
    "defi",
    "infra"
  ],
  "contracts": [
    {
      "tag": "atomiq_bridge",
      "addresses": {
        "mainnet-alpha": [
          "0x04fb26d02d2cf612566cd86cab299716d926272e9f49514670233952ecaf8f0c"
        ]
      },
      "name": "Atomiq Bridge"
    }
  ]
}

=== myBraavos/starknet-meta/repository/ventory/metadata.json
{
    "id": "ventory",
    "displayName": "Ventory",
    "host": "ventory.gg",
    "description":  "Ventory is the cutting-edge protocol that enables NFT enthusiasts to create, trade and earn the latest NFTs designed on the market. Our comprehensive tools enables 721, 404 NFT and derivatives NFT trading on various networks.",
    "categories": ["nft", "infra"],
    "contracts": [
      {
        "tag": "marketplace",
        "addresses": {
          "mainnet-alpha": [
            "0x008755a98ccf7d25e69aa90ef3b73b07c470ba4ec6391b0b0c7c598f992c3fee"
          ]
        }
      }
    ]
  }

=== myBraavos/starknet-meta/repository/carbonable/metadata.json
{
  "id": "carbonable",
  "displayName": "Carbonable",
  "host": "app.carbonable.io",
  "description": "Empower every person and organization to turn ecological intentions into verifiable action",
  "categories": ["defi", "nft"],
  "contracts": [
    {
      "tag": "carbonable_project_721",
      "addresses": {
        "goerli-alpha": [
          "0x02873e0cdbd8bf5d35c794d06b9518c1dcac0f4f4d9f36231c1611ec2b47c95b",
          "0x30f5a9fbcf76e2171e49435f4d6524411231f257a1b28f517cf52f82279c06b"
        ],
        "mainnet-alpha":[
          "0x4047810e4f759336f941a16b6de9d8d2f934e976b9a9431a2964646df9025c6",
          "0xebf4bbab9c934fa0212c9358331d4a9543ad66a7e0007d4a720cfa6b56061e",
          "0x0541b5dd5fae206ceccaf4eeb0642e4c04d456c5bc296eab047c9414bdad4f09",
          "0x6191013bbd6bcf11d69f3d60d20f7aa03439d7011bd511d13122de2275dce21",
          "0x61bcc33b0469cd072ad47813a1efd250fd36a28425d774c31c8f33c87306e8e"


        ]
      }
    },
    {
      "tag": "carbonable_minter_721",
      "addresses": {
        "goerli-alpha": [
          "0x04c78baeeca296374ee430f725ab6deea30f7f9092c78032354b10940bf2d852",
          "0x1258f0aee6c6f5f9c1eb1759406a9337f8c7ffaab08d7ed2488714ab20328d2"
        ],
        "mainnet-alpha":[
          "0x751d90d78f315ca518d8bdbb2a87c822279b89200f43d9a367d849632176da4",
          "0x2f3395e63079818591f240b2fa5fdaef5af7ed81b6783e1ab047259c72f1dff",
          "0x005321d00440218677b1de426679b7e77381dbb846ee1ae54dc084951f99c646",
          "0x03d983ed77d966515c066d49aa35cefffc89231cb33b9593a8964f58eca8ccd8",
          "0x06458bdd463dc9cc8057c586ef5ebd80a6984c5ebcfb7b5271f25dd3d23ddfb1",
          "0x04b13fd9300bf4dbd94a3434455551e3beb424aebfd41962839d60b53a4590b2"

        ]
      }
    },
    {
      "tag": "carbonable_vester_721",
      "addresses": {
        "goerli-alpha": [
          "0x036b1b867383c1ff14ab6762e1f14a427aadc0abd9a7df5233d211e867125911",
          "0x1258f0aee6c6f5f9c1eb1759406a9337f8c7ffaab08d7ed2488714ab20328d2"
        ]
      }
    },
    {
      "tag": "carbonable_offseter_721",
      "addresses": {
        "goerli-alpha": [
          "0x02d5aff6d8a2b16735f0fb5c8cff91fefce7953f0178a14d12092f431e507c56"
        ]
      }
    },
    {
      "tag": "carbonable_yielder_721",
      "addresses": {
        "goerli-alpha": [
          "0x01f837476279407e3deb9afc69291d477d4943ead79723db2cbeca303b539f38"
        ]
      }
    },

    {
      "tag": "carbonable_project_3525",
      "addresses": {
        "goerli-alpha": [
          "0x722559df8b45ed4b82aceeaa08f46111ba6d03419916703c7b6990a8ab7da64",
          "0x0516d0acb6341dcc567e85dc90c8f64e0c33d3daba0a310157d6bba0656c8769",
          "0x05a667adc04676fba78a29371561a0bf91dab25847d5dc4709a93a4cfb5ff293"
        ],
        "mainnet-alpha":[

        ]
      }
    },
    {
      "tag": "carbonable_minter_3525",
      "addresses": {
        "goerli-alpha": [
          "0x068337d9e937a5a5a440b8d520cc43d80913c6d7769f90c3afdfaa1b7e929025"
        ],
        "mainnet-alpha":[
          "0x065ff26209e5b2089e84488568ca84d7981d95f2ccb77f2f39878c4ab98e96cc",
          "0x04673097fab74b77264c05982cd1ee6afaa2ee81787851c3cb47a3ab70357212",
          "0x0645af9030761e0ecacf0f15876b6cc0720f38ba929b22a76697abc2e5ab4ef2",
          "0x07336c28e621dce9940603fb85136c57a3c46ce22e4ec862eeb0bdb0cd5cc9d9"
        ]
      }
    },
    {
      "tag": "carbonable_vester_3525",
      "addresses": {
        "goerli-alpha": [
          "0x5c4c4b0f46b310a2ebec4a4cfadabbebc2eaa8c998b590aa470a848a43b8d29"
        ]
      }
    },
    {
      "tag": "carbonable_offseter_3525",
      "addresses": {
        "goerli-alpha": [
          "0x37c4ec0aba6efb98a476a324f65cc69399d088cea4b5210276b7b5c950feabb",
          "0x032f39e989f21b7b2001e99e5d5f0c3a2aa166fc162dba35a2e4bf58da2a80c2"
        ],
        "mainnet-alpha":[
          "0x0324b531f731100b494e2f978a26b20b5870585dd96d9f1166b43a28ebbb8aba",
          "0x022f40128af9798a0b734874fd993bbab6cf75845f26f844cb151b7041132c6d",
          "0x04258037980fcc15083cde324abe1861ac00d4d48b7d60d76b5efd6f57e59e73"
        ]
      }
    },
    {
      "tag": "carbonable_yielder_3525",
      "addresses": {
        "goerli-alpha": [
          "0x5b2fa5a923d5fecb8ca054bd6925f3361d0d71698441599b071ea7e6390121e",
          "0x000ca9e8277458d3f0340985d25000987400593e116f1a99c429dd5d00363b19"
        ],
        "mainnet-alpha":[
          "0x03d25473be5a6316f351e8f964d0c303357c006f7107779f648d9879b7c6d58a",
          "0x00426d4e86913759bcc49b7f992b1fe62e6571e8f8089c23d95fea815dbad471",
          "0x03afe61732ed9b226309775ac4705129319729d3bee81da5632146ffd72652ae"
        ]
      }
    }

  ]
}

=== myBraavos/starknet-meta/repository/mintsquare/metadata.json
{
  "id": "mintsquare",
  "displayName": "Mint Square",
  "host": "mintsquare.io",
  "description": "NFT marketplace on Ethereum Layer 2 ZK Rollups",
  "categories": [
    "nft",
    "mobile"
  ],
  "contracts": [
    {
      "tag": "mintsquare_collection",
      "implements": [
        "erc721"
      ],
      "addresses": {
        "goerli-alpha": [
          "0x064bfed736951e98e16fedfd4605960879251f59f2f14427a2ae88a48f379801",
          "0x2f13075210b7252c826eafdc09d9d77ef272f582947f7adbd44ef79eae0062c"
        ],
        "mainnet-alpha": [
          "0x07861c4e276294a7e859ff0ae2eec0c68300ad9cbb43219db907da9bad786488",
          "0x04a3621276a83251b557a8140e915599ae8e7b6207b067ea701635c0d509801e"
        ]
      }
    },
    {
      "tag": "mintsquare_marketplace",
      "addresses": {
        "goerli-alpha": [
          "0x033f80aa81bdc938a0793a5bfc879b86c687b366744b16ee03caa68e204c4df2",
          "0x05bc8cc601c5098e20e9d9d74e86cfb0ec737f6f3ac571914dbe4f74aa249786",
          "0x0029fd090a27fc937b6328c89c1a228811c3b221ef5ed19186e08a368de72a2f"
        ],
        "mainnet-alpha": [
          "0x0713273b1982c3b870b963418843ff8cbdb8f92481cd7f663f0f0e1c94848833",
          "0x079b882cb8200c1c1d20e849a2ef19124b0b8985358c1313ea6af588cfe4fec8"
        ]
      }
    },
    {
      "tag": "mintsquare_marketplace_manager",
      "addresses": {
        "goerli-alpha": [
          "0x0423c040595731d6c4a3127e8def5b32b94ea81da8c79c17759202fd7417797c",
          "0x007b1363f50b27bfbba7675a35b13599f8fa11b9483aac072b8c493abae8b5c5"
        ],
        "mainnet-alpha": [
          "0x041682b0bcd5db29046130db68a7f6650433acabc0792db559dac247305df783",
          "0x04767b873669406d25dddbf67356e385a14480979e5358a411955d692576aa30"
        ]
      }
    },
    {
      "tag": "mintsquare_auction_address",
      "addresses": {
        "goerli-alpha": [

          "0x038e8a53c92fff5e797d348b99c23ade60d86b835d61b3b70e5bf7920c623588"
        ],
        "mainnet-alpha": [
          "0x07a16e9f4608c60704d6b1dfcea6354857ce106281b8986ed9afdecff231f957"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/gol2/metadata.json
{
	"id": "gol2",
	"displayName": "GoL2",
	"host": {
		"mainnet-alpha": "www.gol2.io",
		"goerli-alpha": "goerli.gol2.io"
	},
	"description": "An on-chain remix of the classic 'Game of Life' by John Conway on Starknet b\u0000\u0013.",
	"categories": [
		"gamefi"
	],
	"contracts": [{
		"tag": "main",
		"implements": [
			"erc20"
		],
		"addresses": {
			"goerli-alpha": [
				"0x06dc4bd1212e67fd05b456a34b24a060c45aad08ab95843c42af31f86c7bd093"
			],
			"mainnet-alpha": [
				"0x06a05844a03bb9e744479e3298f54705a35966ab04140d3d8dd797c1f6dc49d0"
			]
		}
	}]
}

=== myBraavos/starknet-meta/repository/strkfarm/metadata.json
{
    "id": "strkfarm",
    "displayName": "STRKFarm",
    "host": {
        "mainnet-alpha": "strkfarm.com"
    },
    "description": "STRKFarm is Starknet's ultimate yield aggregator. Find and invest in high yield pools!",
    "categories": [
        "defi"
    ],
    "contracts": [
        {
            "tag": "Master",
            "addresses": {
                "mainnet-alpha": [
                    "0x050314707690c31597849ed66a494fb4279dc060f8805f21593f52906846e28e"
                ]
            }
        },
        {
            "tag": "Auto-Compounding STRK",
            "addresses": {
                "mainnet-alpha": [
                    "0x00541681b9ad63dff1b35f79c78d8477f64857de29a27902f7298f7b620838ea"
                ]
            }
        },
        {
            "tag": "Auto-Compounding USDC",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x016912b22d5696e95ffde888ede4bd69fbbc60c5f873082857a47c543172694f"
                ]
            }
        },
        {
            "tag": "STRK Sensei",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x020d5fc4c9df4f943ebb36078e703369c04176ed00accf290e8295b659d2cea6"
                ]
            }
        },
        {
            "tag": "USDC Sensei",
            "implements": [
                "erc20"
            ],
            "addresses": {
                "mainnet-alpha": [
                    "0x04937b58e05a3a2477402d1f74e66686f58a61a5070fcc6f694fb9a0b3bae422"
                ]
            }
        }
    ]
}
