=== myBraavos/starknet-meta/schemas/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+$"
        },
        "displayName": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,50}$"
        },
        "description": {
            "type": "string",
            "pattern": "^[\\x00-\\x7F]{1,300}$"
        },
        "host": {
            "oneOf": [
                {
                    "$ref": "types.json#/definitions/Host"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "minProperties": 1,
                    "properties": {
                        "mainnet-alpha": {
                            "$ref": "types.json#/definitions/Host"
                        },
                        "goerli-alpha": {
                            "$ref": "types.json#/definitions/Host"
                        },
                        "goerli-alpha-2": {
                            "$ref": "types.json#/definitions/Host"
                        },
                        "others": {
                            "$ref": "types.json#/definitions/Host"
                        }
                    }
                }
            ]
        },
        "contracts": {
            "type": "array",
            "items": {
                "$ref": "types.json#/definitions/Contract"
            }
        },
        "categories": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Category"
            }
        }
    },
    "definitions": {
        "Category": {
            "type": "string",
            "enum": [
                "nft",
                "defi",
                "mobile",
                "infra",
                "gamefi",
                "digitalid"
            ]
        }
    },
    "required": [
        "id",
        "displayName",
        "description",
        "host",
        "contracts",
        "categories"
    ]
}

=== myBraavos/starknet-meta/repository/endur/metadata.json
{
    "id": "endur",
    "displayName": "Endur",
    "host": {
        "mainnet-alpha": "app.endur.fi",
        "sepolia-alpha": "testnet.endur.fi"
    },
    "description": "Endur is a platform offering xSTRK, a tradeable Liquid Staking Token (LST) on Starknet. xSTRK allows STRK token holders to stake their assets while maintaining liquidity.",
    "categories": [
        "defi"
    ],
    "contracts": [
        {
            "tag": "xSTRK Token Contract",
            "addresses": {
                "mainnet-alpha": [
                    "0x28d709c875c0ceac3dce7065bec5328186dc89fe254527084d1689910954b0a"
                ],
                "sepolia-alpha": [
                    "0x42de5b868da876768213c48019b8d46cd484e66013ae3275f8a4b97b31fc7eb"
                ]
            }
        },
        {
            "tag": "Withdraw Queue NFT",
            "addresses": {
                "mainnet-alpha": [
                    "0x518a66e579f9eb1603f5ffaeff95d3f013788e9c37ee94995555026b9648b6"
                ],
                "sepolia-alpha": [
                    "0x254cbdaf8275cb1b514ae63ccedb04a3a9996b1489829e5d6bbaf759ac100b6"
                ]
            }
        }
    ]
}

=== myBraavos/starknet-meta/repository/strkstaking/metadata.json
{
    "id": "strkstaking",
    "displayName": "STRK Staking",
    "host": "braavos.app",
    "description": "Stark Staking allows you to stake your STRK tokens and enjoy staking rewards",
    "categories": ["defi"],
    "contracts": [
        {
            "tag": "strk_staking_contract",
            "addresses": {
                "mainnet-alpha": [
                    "0xca1702e64c81d9a07b86bd2c540188d92a2c73cf5cc0e508d949015e7e84a7"
                ],
                "sepolia-alpha": [
                    "0x3745ab04a431fc02871a139be6b93d9260b0ff3e779ad9c8b377183b23109f1"
                ]
            }
        },
        {
            "tag": "braavos_staking_pool",
            "name": "Braavos",
            "addresses": {
                "mainnet-alpha": [
                    "0x1f170bafce432964d6cbaf2cb75355b2043f5640897e0623b7dbb029bf6b3ef"
                ],
                "sepolia-alpha": [
                    "0x30bbb25449b910ca6b8cb5de138a34cad956df326fc697623ff6b856e657377"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/braavos_pool_icon.svg"
        },
        {
            "tag": "karnot_staking_pool",
            "name": "Karnot",
            "addresses": {
                "mainnet-alpha": [
                    "0x7d695337550e96e1372dd03274965cca0284ded266efc1774d001d37fbca104"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/karnot_pool_icon.svg"
        },
        {
            "tag": "satoshi_university_staking_pool",
            "name": "Satoshi University",
            "addresses": {
                "mainnet-alpha": [
                    "0x69bd0141acecdc330ff8daf8f70f3ccad984ce3a8f015b7386f870309f7da63"
                ]
            }
        },
        {
            "tag": "avnu_staking_pool",
            "name": "AVNU",
            "addresses": {
                "mainnet-alpha": [
                    "0x362dc7da60bfddc8e3146028dfd94941c6e22403c98b5947104e637543b475d"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/avnu_pool_icon.svg"
        },
        {
            "tag": "nimbora_staking_pool",
            "name": "Nimbora",
            "addresses": {
                "mainnet-alpha": [
                    "0x1d1ba466d60c0288dcb2a52b406bacc14c655d7ea98503e9dcdaaff59ed19db"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/nimbora_pool_icon.svg"
        },
        {
            "tag": "p2p_staking_pool",
            "name": "P2P.org",
            "addresses": {
                "mainnet-alpha": [
                    "0x7c744f9bfc2555505dd92399048ec792886a822b26a828496405a57e30a0e0d"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/p2p_pool_icon.svg"
        },
        {
            "tag": "infstones_staking_pool",
            "name": "InfStones",
            "addresses": {
                "mainnet-alpha": [
                    "0x6cc852d7752e9e69cd4d3e02b1cbcdd4dd9607511a74efb3d90f2490d8b4240"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/infstones_pool_icon.svg"
        },
        {
            "tag": "teku_staking_pool",
            "name": "Teku",
            "addresses": {
                "mainnet-alpha": [
                    "0x1c202d2a02866c57d4950a461c1e870ace37a07ebcf2d92c62764f768233692"
                ]
            },
            "icon": "https://raw.githubusercontent.com/myBraavos/starknet-meta/main/repository/strkstaking/teku_pool_icon.svg"
        }
    ]
}

=== myBraavos/starknet-meta/repository/lootsurvivor/metadata.json
{
  "id": "lootsurvivor",
  "displayName": "Loot Survivor",
  "host": {
    "goerli-alpha": "goerli-survivor.realms.world",
    "mainnet-alpha": "survivor.realms.world",
    "sepolia-alpha": "sepolia-survivor.realms.world"
  },
  "description": "Loot Survivor is an onchain Arcade machine game, first of the Play2Die franchise. You add some tokens, try to get the highscore and live for eternity onchain.",
  "categories": [
    "gamefi", "nft", "mobile"
  ],
  "contracts": [
    {
      "tag": "loot_survivor_game",
      "addresses": {
        "goerli-alpha": [
          "0x071d07b1217cdcc334739a3f28da75db05d62672ad04b9204ee11b88f2f9f61c"
        ],
        "mainnet-alpha": [
          "0x03c10537fa0073b2dd5120242697dbf76d6173eb9f384d3bf3d284d53388a0b0"
        ],
        "sepolia-alpha": [
          "0x0713063bab72fb1ff6aa279f53962f3adf0154305b194da42e8d20562f61c5fd"
        ]
      }
    },
    {
      "tag": "loot_survivor_beasts",
      "addresses": {
        "goerli-alpha": [
          "0x05c909139dbef784180eef8ce7a2f5bf52afe567aa73aaa77b8d8243ad5b6b96"
        ],
        "mainnet-alpha": [
          "0x0158160018d590d93528995b340260e65aedd76d28a686e9daa5c4e8fad0c5dd"
        ],
        "sepolia-alpha": [
          "0x03065c1db93be057c40fe92c9cba7f898de8d3622693d128e4e97fdc957808a3"
        ]
      }
    },
    {
      "tag": "loot_survivor_golden_token",
      "addresses": {
        "goerli-alpha": [
          "0x003583470a8943479f8609192da4427cac45bdf66a58c84043c7ab2fc722c0c0"
        ],
        "mainnet-alpha": [
          "0x04f5e296c805126637552cf3930e857f380e7c078e8f00696de4fc8545356b1d"
        ],
        "sepolia-alpha": [
          "0x024f21982680442892d2f7ac4cee98c7d62708b04fdf9f8a0453415baca4b16f"
        ]
      }
    },
    {
      "tag": "lords",
      "addresses": {
        "goerli-alpha": [
          "0x05e367ac160e5f90c5775089b582dfc987dd148a5a2f977c49def2a6644f724b"
        ],
        "mainnet-alpha": [
          "0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49"
        ],
        "sepolia-alpha": [
          "0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210"
        ]
      }
    }
  ]
}

=== myBraavos/starknet-meta/repository/remusdex/metadata.json
{
  "id": "remusdex",
  "displayName": "RemusDEX",
  "host": "app.remusdex.xyz",
  "description": "RemusDEX redefines trading with a user-centric order book experience, combining the speed of Starknet with the trust of decentralization.",
  "categories": [
    "defi"
  ],
  "contracts": [
    {
      "tag": "remus_dex_singleton",
      "addresses": {
        "sepolia-alpha": [
          "0x04e1ac8fe63b465a583740a684aeff3589428d50869b79da2dd296c380ee4bd8"
        ],
        "mainnet-alpha": [
          "0x067e7555f9ff00f5c4e9b353ad1f400e2274964ea0942483fae97363fd5d7958"
        ]
      }
    }
  ]
}
